name: Build and deploy app_aws

on:
  push:
    branches:  [ main ]
    paths:
      - 'app_aws/**'
      - '.github/workflows/aws.yaml'

jobs: # <--- Тільки ОДИН РАЗ на весь файл
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: app_aws
        run: |
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: app_aws/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: app_aws/dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Identity Check
        run: aws sts get-caller-identity    
      - name: Sync dist to S3
        run: aws s3 sync app_aws/dist s3://${{ secrets.AWS_S3_BUCKET }}



















# : Build and deploy app_aws

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'app_aws/**'
#       - '.github/workflows/aws.yaml'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Use Node.js 20
#         uses: actions/setup-node@v5
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         working-directory: app_aws
#         run: npm ci

#       - name: Build app
#         working-directory: app_aws
#         run: npm run build

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - uses: actions/checkout@v4

#       - name: Sync dist to S3
#         uses: jakejarvis/s3-sync-action@v0.5.1
#         with:
#           args: --acl public-read --delete
#           source_dir: app_aws/dist
#         env:
#           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}